=== uo251119/sew/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://uo251119/rutas" elementFormDefault="qualified"
    targetNamespace="http://uo251119/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ruta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="tipo" />
                <xs:element ref="medioTransporte" />
                <xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
                <xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
                <xs:element ref="duracion" />
                <xs:element ref="agencia" />
                <xs:element ref="descripcion" />
                <xs:element ref="personasAdecuadas" />
                <xs:element ref="lugarInicio" />
                <xs:element ref="direccionInicio" />
                <xs:element ref="coordenadas" />
                <xs:element ref="recomendacion" />
                <xs:element ref="referencias" />
                <xs:element ref="hitos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string" />
    <xs:element name="tipo" type="xs:string" />
    <xs:element name="medioTransporte" type="xs:string" />
    <xs:element name="fechaInicio" type="xs:date" />
    <xs:element name="horaInicio" type="xs:time" />
    <xs:element name="duracion" type="xs:string" />
    <xs:element name="agencia" type="xs:string" />
    <xs:element name="descripcion" type="xs:string" />
    <xs:element name="personasAdecuadas" type="xs:string" />
    <xs:element name="lugarInicio" type="xs:string" />
    <xs:element name="direccionInicio" type="xs:string" />
    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="latitud" />
                <xs:element ref="longitud" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="latitud" type="xs:decimal" />
    <xs:element name="longitud" type="xs:decimal" />
    <xs:element name="altitud" type="xs:integer" />
    <xs:element name="recomendacion" type="xs:string" />
    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="referencia" type="xs:string" />
    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="descripcion" />
                <xs:element ref="coordenadas" />
                <xs:element ref="distanciaHitoAnterior" />
                <xs:element ref="fotografias" />
                <xs:element minOccurs="0" maxOccurs="1" ref="videos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="distanciaHitoAnterior">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="unidades" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="fotografias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="fotografia" type="xs:string" />
    <xs:element name="videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="3" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="video" type="xs:string" />
</xs:schema>

=== uo251119/sew/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas
    xmlns="http://uo251119/rutas"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://uo251119/rutas rutas.xsd">
    <ruta>
        <nombre>Ruta de La Parroquia</nombre>
        <tipo>Arquitectura y monumentos</tipo>
        <medioTransporte>A pie</medioTransporte>
        <fechaInicio>2024-05-05</fechaInicio>
        <horaInicio>08:00:00</horaInicio>
        <duracion>4 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion> Es el país más pequeño del continente americano, tanto en tamaño como en
            población por lo que es considerado un microestado. San Cristóbal y Nieves poseen una
            superficie de 261 kilómetros cuadrados y una población de 54.961 habitantes. Su capital
            y ciudad más poblada es Basseterre, en San Cristóbal. </descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Parroquia de Saint Thomas Middle Island</lugarInicio>
        <direccionInicio>Saint Thomas Middle Island</direccionInicio>
        <coordenadas>
            <latitud>17.341180</latitud>
            <longitud>-62.795681</longitud>
            <altitud>1000</altitud>
        </coordenadas>
        <recomendacion>9</recomendacion>
        <referencias>
            <referencia> https://es.wikiloc.com/rutas/outdoor/san-cristobal-y-nieves</referencia>
            <referencia>
                https://www.exteriores.gob.es/Documents/FichasPais/SANCRISTOBALYNIEVES_FICHA%20PAIS.pdf</referencia>
            <referencia>https://observatorioplanificacion.cepal.org/es/paises/san-cristobal-y-nieves</referencia>
        </referencias>
        <hitos>
            <hito>
                <nombre>Parroquia de Saint Thomas Middle Island</nombre>
                <descripcion>Excelentes vistas del amanecer</descripcion>
                <coordenadas>
                    <latitud>17.341180</latitud>
                    <longitud>-62.795681</longitud>
                    <altitud>1000</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">500</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>parroquia_saint_thomas.jpg</fotografia>
                    <fotografia>saint_thomas_map.png</fotografia>
                </fotografias>
                <videos>
                    <video>saint_thomas.mp4</video>
                </videos>
            </hito>
            <hito>
                <nombre>Parroquia de Chist Church Nichola Town</nombre>
                <descripcion>Vistas al río</descripcion>
                <coordenadas>
                    <latitud>17.369206</latitud>
                    <longitud>-62.774445</longitud>
                    <altitud>1500</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">600</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>nichola_town.jpg</fotografia>
                </fotografias>
            </hito>
            <hito>
                <nombre>Parroquia de Saint George Basseterre</nombre>
                <descripcion>Finalizamos la ruta descansando con las vistas</descripcion>
                <coordenadas>
                    <latitud>17.282227</latitud>
                    <longitud>-62.682328</longitud>
                    <altitud>1300</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">300</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>saint_george.jpeg</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>

    <ruta>
        <nombre>Ruta de Cliftons</nombre>
        <tipo>Senderismo</tipo>
        <medioTransporte>A pie o bicicleta</medioTransporte>
        <fechaInicio>2024-05-15</fechaInicio>
        <horaInicio>12:00:00</horaInicio>
        <duracion>4 horas</duracion>
        <agencia>NaturAller</agencia>
        <descripcion> Los primeros nativos que vivieron en las islas, hace ya 3.000 años, se
            llamaban Ciboney. Sin embargo, la falta de cerámica hace que su origen y cronología sean
            inciertos. Les siguieron los pueblos arawak o taínos en el año 800 d.C. </descripcion>
        <personasAdecuadas>Cualquier persona</personasAdecuadas>
        <lugarInicio>Cliftons</lugarInicio>
        <direccionInicio>Cliftons centro Cultural</direccionInicio>
        <coordenadas>
            <latitud>17.181362</latitud>
            <longitud>-62.603211</longitud>
            <altitud>2000</altitud>
        </coordenadas>
        <recomendacion>8</recomendacion>
        <referencias>
            <referencia>https://observatorioplanificacion.cepal.org/es/paises/san-cristobal-y-nieves</referencia>
            <referencia>https://www.villacondide.com</referencia>
            <referencia>https://www.datosmundial.com/america/cristobal-nieves/index.php</referencia>
        </referencias>
        <hitos>
            <hito>
                <nombre>Cliftons centro Cultural</nombre>
                <descripcion>Inicio de la ruta</descripcion>
                <coordenadas>
                    <latitud>17.181362</latitud>
                    <longitud>-62.603211</longitud>
                    <altitud>2050</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">2000</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>cliftons.png</fotografia>
                </fotografias>
            </hito>
            <hito>
                <nombre>Área recreativa de Vaughans</nombre>
                <descripcion>Para descansar</descripcion>
                <coordenadas>
                    <latitud>17.153665</latitud>
                    <longitud>-62.606885</longitud>
                    <altitud>1700</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="km">50</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>vaughans.png</fotografia>
                </fotografias>
            </hito>
            <hito>
                <nombre>Parroquia de Saint John Figtree</nombre>
                <descripcion>Final de la ruta</descripcion>
                <coordenadas>
                    <latitud>17.115820</latitud>
                    <longitud>-62.620359</longitud>
                    <altitud>4200</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">10</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>saint_john_figtree.png</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>

    <ruta>
        <nombre>Ruta de Rices</nombre>
        <tipo>Senderismo</tipo>
        <medioTransporte>A pie</medioTransporte>
        <fechaInicio>2024-06-01</fechaInicio>
        <horaInicio>09:00:00</horaInicio>
        <duracion>3 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Familiar y amigos</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Coaña</lugarInicio>
        <direccionInicio>Estilleiro</direccionInicio>
        <coordenadas>
            <latitud>17.121516</latitud>
            <longitud>-62.558844</longitud>
            <altitud>200</altitud>
        </coordenadas>
        <recomendacion>7</recomendacion>
        <referencias>
            <referencia>
                https://www.tripadvisor.es/Attractions-g147373-Activities-St_Kitts_and_Nevis.html</referencia>
            <referencia>https://www.airbnb.es/saint-kitts-and-nevis/stays</referencia>
            <referencia> https://www.fundeu.es/recomendacion/saint-kitts-y-nevis/</referencia>
        </referencias>
        <hitos>
            <hito>
                <nombre>Rices</nombre>
                <descripcion>Disfrute de la vista</descripcion>
                <coordenadas>
                    <latitud>17.121516</latitud>
                    <longitud>-62.558844</longitud>
                    <altitud>200</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">110</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>rices.png</fotografia>
                </fotografias>
            </hito>
            <hito>
                <nombre>Mannings</nombre>
                <descripcion>Disfrute de la vista de Mannings.</descripcion>
                <coordenadas>
                    <latitud>17.148090</latitud>
                    <longitud>-62.563994</longitud>
                    <altitud>500</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">300</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>mannings.png</fotografia>
                </fotografias>
            </hito>
            <hito>
                <nombre>Rawlins</nombre>
                <descripcion>Disfrute del relajante sonido del agua</descripcion>
                <coordenadas>
                    <latitud>17.178926</latitud>
                    <longitud>-62.579443</longitud>
                    <altitud>700</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">500</distanciaHitoAnterior>
                <fotografias>
                    <fotografia>rawlins.png</fotografia>
                </fotografias>
            </hito>
        </hitos>
    </ruta>
</rutas>
